name: Deploy

on:
  push:
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
    branches:
      - master
      - gp-pages-preview

concurrency:
  group: seaql.github.io
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: sh build.sh

      - uses: rossjrw/pr-preview-action@v1
        with:
          preview-branch: gh-pages
          source-dir: .
          umbrella-dir: pr-preview
          action: auto

      # - run: cp -rf ./build/* ./docs/

      # - uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     branch: gh-pages
      #     folder: .
      #     single-commit: true
      #     clean: true
      #     clean-exclude: pr-preview
